// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';
// ignore: unused_import
import 'firebase_options.dart';
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmLHreilojjPzsTGdoPtqazkHjUugZsjI',
    appId: '1:674597104380:web:ba0d6965cf4726c1c08579',
    messagingSenderId: '674597104380',
    projectId: 'catatan-883db',
    authDomain: 'catatan-883db.firebaseapp.com',
    storageBucket: 'catatan-883db.appspot.com',
    measurementId: 'G-TKSCFKT3L8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Klw3lOxo4VcuTthTH1KWUK8GVFN9ANg',
    appId: '1:674597104380:android:4e600ffd4983079ec08579',
    messagingSenderId: '674597104380',
    projectId: 'catatan-883db',
    storageBucket: 'catatan-883db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgK6CVC89DWLRu5cYqLiWnDInTKVoQYoI',
    appId: '1:674597104380:ios:8a95dde5f31c07e6c08579',
    messagingSenderId: '674597104380',
    projectId: 'catatan-883db',
    storageBucket: 'catatan-883db.appspot.com',
    iosBundleId: 'com.example.catatanmahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgK6CVC89DWLRu5cYqLiWnDInTKVoQYoI',
    appId: '1:674597104380:ios:6d102e879550f23ac08579',
    messagingSenderId: '674597104380',
    projectId: 'catatan-883db',
    storageBucket: 'catatan-883db.appspot.com',
    iosBundleId: 'com.example.catatanmahasiswa.RunnerTests',
  );
}
